packages:
  - app
  - docs
  - apps/**
  - packages/**
  - '!**/test/**'

onlyBuiltDependencies:
  - '@mediago/core'
  - '@mediago/player'
  - '@parcel/watcher'
  - '@swc/core'
  - '@tailwindcss/oxide'
  - better-sqlite3
  - electron
  - esbuild
