packages:
  - app
  - docs
  - apps/**
  - packages/**
  - "!**/test/**"
  - "!**/release/**"

onlyBuiltDependencies:
  - "@mediago/core"
  - "@mediago/deps"
  - "@mediago/player"
  - "@parcel/watcher"
  - "@swc/core"
  - "@tailwindcss/oxide"
  - better-sqlite3
  - core-js
  - electron
  - es5-ext
  - esbuild
