packages:
  - app
  - docs
  - apps/**
  - packages/**
  - '!**/test/**'
  - '!**/release/**'

onlyBuiltDependencies:
  - '@mediago/core'
  - '@mediago/deps'
  - '@mediago/player'
  - '@parcel/watcher'
  - '@sentry-internal/node-cpu-profiler'
  - '@swc/core'
  - '@tailwindcss/oxide'
  - better-sqlite3
  - core-js
  - electron
  - electron-winstaller
  - es5-ext
  - esbuild
