version: '3.8'

services:
  webapi:
    build:
      context: ../
      dockerfile: docker/Dockerfile.dev
    ports:
      - "8899:8899"
    volumes:
      - mediago-data:/app/data
    environment:
      - NODE_ENV=development
    networks:
      - mediago-network

volumes:
  mediago-data:

networks:
  mediago-network:
    driver: bridge
